# Change these first
owner: DikaArdnt # Your GitHub organization or username, where this repository lives
repo: upptimeku # The name of this repository

sites:
   - name: Dika Ardnt Site
     url: https://dikaardnt.com
   - name: REST API
     url: https://dikaardnt.com/api/server
     expectedStatusCodes:
        - 200
        - 429
        - 400
        - 404
   - name: Quote API
     method: POST
     url: https://dikaardnt.com/api/maker/quote
     expectedStatusCodes:
        - 400
        - 429
        - 200
   - name: WhatsApp Bot Hosting
     url: https://hisoka.net/api
     expectedStatusCodes:
        - 400
        - 429
        - 200
        - 404

status-website:
   # Add your custom domain name, or remove the `cname` line if you don't have a domain
   cname: status.dikaardnt.com
   # baseUrl: /upptimeku
   logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
   name: Upptimeku
   introTitle: '**Upptimeku**'
   introMessage: Dika Ardnt's status page, with real-time response times, uptime and status history.
   navbar:
      - title: Status
        href: /
      - title: GitHub
        href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
